### ISSUE TITLE
服务器执行npm install，出现以下错误

### ISSUE THREAD

**Issue by JustForLucky** [antvis/adjust#12]
mnpm ERR! network request to https://registry.npm.alibaba-inc.com/@antv/adjust/download/@antv/adjust-0.2.3.tgz failed, reason: connect ETIMEDOUT 103.52.199.227:443

**Comment by hustcc** [comment]
确实已经发布了 0.2.3 版本。https://www.npmjs.com/package/@antv/adjust

可能的问题：

1. 内部源是否同步
2. 网络是否联通
